import { drizzle } from "drizzle-orm/neon-serverless";
import { clients, users, activities } from "../shared/schema";
import ws from "ws";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is required");
}

const db = drizzle({
  connection: process.env.DATABASE_URL,
  ws: ws,
});

const sampleUsers = [
  { name: "Sarah Johnson", email: "sarah@company.com", role: "Sales Rep" as const },
  { name: "Mike Davis", email: "mike@company.com", role: "Manager" as const },
  { name: "Tom Williams", email: "tom@company.com", role: "Sales Rep" as const },
  { name: "Jennifer Lee", email: "jennifer@company.com", role: "Sales Rep" as const },
  { name: "Alex Martinez", email: "alex@company.com", role: "Sales Rep" as const },
];

const buildSampleClients = (userIds: string[]) => [
  {
    companyName: "Acme Corporation",
    contactPerson: "John Smith",
    email: "john@acme.com",
    phone: "+1 234-567-8900",
    stage: "Qualified" as const,
    status: "In Negotiation" as const,
    value: "250000",
    lastFollowUp: new Date("2025-11-15"),
    nextFollowUp: new Date("2025-11-22"),
    priority: "High" as const,
    responsiblePersonId: userIds[0],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/johnsmith",
    notes: "Interested in enterprise package. Decision maker meeting scheduled.",
    source: "Referral" as const,
    industry: "Technology",
    estimatedCloseDate: new Date("2025-12-01"),
    winProbability: 75,
  },
  {
    companyName: "TechStart Inc",
    contactPerson: "Emily Chen",
    email: "emily@techstart.com",
    phone: "+1 555-123-4567",
    stage: "Proposal Sent" as const,
    status: "Proposal Rejected" as const,
    value: "180000",
    lastFollowUp: new Date("2025-11-16"),
    nextFollowUp: new Date("2025-11-23"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[2],
    country: "Canada",
    linkedin: "https://www.linkedin.com/in/emilychen",
    notes: "Looking for more flexible pricing options.",
    source: "Website" as const,
    industry: "SaaS",
    estimatedCloseDate: null,
    winProbability: 30,
  },
  {
    companyName: "Global Solutions Ltd",
    contactPerson: "Robert Taylor",
    email: "robert@globalsolutions.com",
    phone: "+1 555-987-6543",
    stage: "Won" as const,
    status: "On Hold" as const,
    value: "420000",
    lastFollowUp: new Date("2025-11-17"),
    nextFollowUp: new Date("2025-11-24"),
    priority: "High" as const,
    responsiblePersonId: userIds[1],
    country: "United Kingdom",
    linkedin: "https://www.linkedin.com/in/roberttaylor",
    notes: "Contract signed. Awaiting project kick-off.",
    source: "Event" as const,
    industry: "Consulting",
    estimatedCloseDate: new Date("2025-11-17"),
    winProbability: 100,
  },
  {
    companyName: "Innovation Hub",
    contactPerson: "Lisa Anderson",
    email: "lisa@innovationhub.com",
    phone: "+1 555-456-7890",
    stage: "Lead" as const,
    status: null,
    value: "95000",
    lastFollowUp: new Date("2025-11-14"),
    nextFollowUp: new Date("2025-11-21"),
    priority: "Low" as const,
    responsiblePersonId: userIds[3],
    country: "Australia",
    linkedin: "",
    notes: "Initial contact made. Needs more information.",
    source: "Cold Outreach" as const,
    industry: "Retail",
    estimatedCloseDate: null,
    winProbability: 20,
  },
  {
    companyName: "FutureTech Systems",
    contactPerson: "David Wu",
    email: "david@futuretech.com",
    phone: "+1 555-789-0123",
    stage: "Proposal Sent" as const,
    status: "In Negotiation" as const,
    value: "320000",
    lastFollowUp: new Date("2025-11-18"),
    nextFollowUp: new Date("2025-11-25"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    country: "Singapore",
    linkedin: "https://www.linkedin.com/in/davidwu",
    notes: "Strong interest. Reviewing technical requirements.",
    source: "Partner" as const,
    industry: "Manufacturing",
    estimatedCloseDate: new Date("2025-12-15"),
    winProbability: 65,
  },
  {
    companyName: "Metro Banking Group",
    contactPerson: "Patricia Williams",
    email: "patricia@metrobank.com",
    phone: "+1 415-555-0100",
    stage: "Qualified" as const,
    status: "In Negotiation" as const,
    value: "580000",
    lastFollowUp: new Date("2025-11-19"),
    nextFollowUp: new Date("2025-11-26"),
    priority: "High" as const,
    responsiblePersonId: userIds[0],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/patriciawilliams",
    notes: "Large enterprise deal. Requires compliance review and multiple stakeholder approval.",
    source: "Referral" as const,
    industry: "Financial Services",
    estimatedCloseDate: new Date("2026-01-15"),
    winProbability: 80,
  },
  {
    companyName: "HealthPlus Medical",
    contactPerson: "Dr. Michael Chang",
    email: "mchang@healthplus.com",
    phone: "+1 617-555-0200",
    stage: "Lead" as const,
    status: null,
    value: "125000",
    lastFollowUp: new Date("2025-11-10"),
    nextFollowUp: new Date("2025-11-20"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[2],
    country: "United States",
    linkedin: "",
    notes: "Healthcare provider looking for patient management system.",
    source: "Website" as const,
    industry: "Healthcare",
    estimatedCloseDate: new Date("2026-02-01"),
    winProbability: 40,
  },
  {
    companyName: "EcoEnergy Solutions",
    contactPerson: "Sandra Martinez",
    email: "sandra@ecoenergy.com",
    phone: "+1 303-555-0300",
    stage: "Proposal Sent" as const,
    status: "In Negotiation" as const,
    value: "275000",
    lastFollowUp: new Date("2025-11-17"),
    nextFollowUp: new Date("2025-11-24"),
    priority: "High" as const,
    responsiblePersonId: userIds[1],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/sandramartinez",
    notes: "Renewable energy company. Very interested in sustainability features.",
    source: "Event" as const,
    industry: "Energy",
    estimatedCloseDate: new Date("2025-12-20"),
    winProbability: 70,
  },
  {
    companyName: "Digital Media Pro",
    contactPerson: "James Thompson",
    email: "james@digitalmedia.com",
    phone: "+1 212-555-0400",
    stage: "Lead" as const,
    status: null,
    value: "90000",
    lastFollowUp: new Date("2025-11-12"),
    nextFollowUp: new Date("2025-11-19"),
    priority: "Low" as const,
    responsiblePersonId: userIds[3],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/jamesthompson",
    notes: "Small marketing agency. Budget constraints noted.",
    source: "Cold Outreach" as const,
    industry: "Marketing",
    estimatedCloseDate: null,
    winProbability: 25,
  },
  {
    companyName: "Phoenix Logistics",
    contactPerson: "Carlos Rodriguez",
    email: "carlos@phoenixlog.com",
    phone: "+52 55-5555-0500",
    stage: "Qualified" as const,
    status: "In Negotiation" as const,
    value: "340000",
    lastFollowUp: new Date("2025-11-18"),
    nextFollowUp: new Date("2025-11-25"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    country: "Mexico",
    linkedin: "https://www.linkedin.com/in/carlosrodriguez",
    notes: "International logistics company expanding to North America. Multi-location deployment.",
    source: "Partner" as const,
    industry: "Logistics",
    estimatedCloseDate: new Date("2026-01-10"),
    winProbability: 60,
  },
  {
    companyName: "BlueSky Aviation",
    contactPerson: "Amanda Foster",
    email: "amanda@blueskyair.com",
    phone: "+1 404-555-0600",
    stage: "Won" as const,
    status: null,
    value: "650000",
    lastFollowUp: new Date("2025-11-15"),
    nextFollowUp: new Date("2025-12-01"),
    priority: "High" as const,
    responsiblePersonId: userIds[0],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/amandafoster",
    notes: "Contract finalized. Implementation starts December 1st. Requires on-site training.",
    source: "Referral" as const,
    industry: "Aviation",
    estimatedCloseDate: new Date("2025-11-15"),
    winProbability: 100,
  },
  {
    companyName: "Quantum Analytics",
    contactPerson: "Dr. Raj Patel",
    email: "raj@quantumanalytics.com",
    phone: "+91 22-5555-0700",
    stage: "Proposal Sent" as const,
    status: "Proposal Rejected" as const,
    value: "210000",
    lastFollowUp: new Date("2025-11-16"),
    nextFollowUp: new Date("2025-12-01"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[2],
    country: "India",
    linkedin: "https://www.linkedin.com/in/rajpatel",
    notes: "Pricing too high for current budget. May revisit in Q1 2026.",
    source: "Website" as const,
    industry: "Data Analytics",
    estimatedCloseDate: null,
    winProbability: 15,
  },
  {
    companyName: "Prime Real Estate Group",
    contactPerson: "Michelle Lee",
    email: "michelle@primerealestate.com",
    phone: "+1 310-555-0800",
    stage: "Qualified" as const,
    status: "In Negotiation" as const,
    value: "195000",
    lastFollowUp: new Date("2025-11-19"),
    nextFollowUp: new Date("2025-11-26"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[1],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/michellelee",
    notes: "Commercial real estate firm. Interested in CRM integration with their property management system.",
    source: "Event" as const,
    industry: "Real Estate",
    estimatedCloseDate: new Date("2025-12-30"),
    winProbability: 55,
  },
  {
    companyName: "Nordic Manufacturing",
    contactPerson: "Lars Andersson",
    email: "lars@nordicmfg.com",
    phone: "+46 8-555-0900",
    stage: "Lead" as const,
    status: null,
    value: "410000",
    lastFollowUp: new Date("2025-11-13"),
    nextFollowUp: new Date("2025-11-27"),
    priority: "High" as const,
    responsiblePersonId: userIds[3],
    country: "Sweden",
    linkedin: "https://www.linkedin.com/in/larsandersson",
    notes: "Large manufacturing operation. Requires multi-language support and EU data compliance.",
    source: "Partner" as const,
    industry: "Manufacturing",
    estimatedCloseDate: new Date("2026-03-01"),
    winProbability: 50,
  },
  {
    companyName: "StarBridge Telecommunications",
    contactPerson: "Kevin O'Brien",
    email: "kevin@starbridge.com",
    phone: "+353 1-555-1000",
    stage: "Proposal Sent" as const,
    status: "On Hold" as const,
    value: "525000",
    lastFollowUp: new Date("2025-11-18"),
    nextFollowUp: new Date("2025-12-02"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    country: "Ireland",
    linkedin: "https://www.linkedin.com/in/kevinobrien",
    notes: "Internal restructuring delayed decision. Very interested but waiting for new fiscal year.",
    source: "Referral" as const,
    industry: "Telecommunications",
    estimatedCloseDate: new Date("2026-01-15"),
    winProbability: 70,
  },
  {
    companyName: "Oceanic Research Institute",
    contactPerson: "Dr. Maria Santos",
    email: "maria@oceanicresearch.org",
    phone: "+55 21-555-1100",
    stage: "Lead" as const,
    status: null,
    value: "85000",
    lastFollowUp: new Date("2025-11-11"),
    nextFollowUp: new Date("2025-11-25"),
    priority: "Low" as const,
    responsiblePersonId: userIds[0],
    country: "Brazil",
    linkedin: "",
    notes: "Non-profit research organization. Grant-dependent budget.",
    source: "Website" as const,
    industry: "Research",
    estimatedCloseDate: null,
    winProbability: 30,
  },
  {
    companyName: "Velocity Sports Management",
    contactPerson: "Derek Johnson",
    email: "derek@velocitysports.com",
    phone: "+1 702-555-1200",
    stage: "Qualified" as const,
    status: "In Negotiation" as const,
    value: "160000",
    lastFollowUp: new Date("2025-11-19"),
    nextFollowUp: new Date("2025-11-26"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[2],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/derekjohnson",
    notes: "Sports talent agency. Needs mobile-first solution for agents in the field.",
    source: "Cold Outreach" as const,
    industry: "Sports & Entertainment",
    estimatedCloseDate: new Date("2026-01-20"),
    winProbability: 45,
  },
  {
    companyName: "Silverline Insurance",
    contactPerson: "Rebecca Zhang",
    email: "rebecca@silverlineins.com",
    phone: "+1 972-555-1300",
    stage: "Won" as const,
    status: null,
    value: "385000",
    lastFollowUp: new Date("2025-11-14"),
    nextFollowUp: new Date("2025-11-28"),
    priority: "High" as const,
    responsiblePersonId: userIds[1],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/rebeccazhang",
    notes: "Deal closed. Regional insurance provider. Implementation phase starting.",
    source: "Event" as const,
    industry: "Insurance",
    estimatedCloseDate: new Date("2025-11-14"),
    winProbability: 100,
  },
  {
    companyName: "Alpine Construction Group",
    contactPerson: "Stefan Mueller",
    email: "stefan@alpineconstruction.com",
    phone: "+41 44-555-1400",
    stage: "Proposal Sent" as const,
    status: "In Negotiation" as const,
    value: "295000",
    lastFollowUp: new Date("2025-11-17"),
    nextFollowUp: new Date("2025-11-24"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[3],
    country: "Switzerland",
    linkedin: "https://www.linkedin.com/in/stefanmueller",
    notes: "Construction management company. Evaluating against two competitors.",
    source: "Partner" as const,
    industry: "Construction",
    estimatedCloseDate: new Date("2026-02-15"),
    winProbability: 50,
  },
  {
    companyName: "Nexus Education Platform",
    contactPerson: "Priya Sharma",
    email: "priya@nexusedu.com",
    phone: "+65 6555-1500",
    stage: "Qualified" as const,
    status: "In Negotiation" as const,
    value: "225000",
    lastFollowUp: new Date("2025-11-18"),
    nextFollowUp: new Date("2025-11-25"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    country: "Singapore",
    linkedin: "https://www.linkedin.com/in/priyasharma",
    notes: "EdTech startup scaling rapidly. Strong growth potential for upsell opportunities.",
    source: "Referral" as const,
    industry: "Education Technology",
    estimatedCloseDate: new Date("2025-12-10"),
    winProbability: 75,
  },
];

async function seed() {
  console.log("Starting database seed...");
  
  try {
    console.log("Seeding users...");
    const insertedUsers = await db.insert(users).values(sampleUsers).onConflictDoNothing().returning();
    
    let finalUsers = insertedUsers;
    if (insertedUsers.length === 0) {
      console.log("Users already exist, fetching them...");
      finalUsers = await db.select().from(users);
    }
    console.log(`Users ready: ${finalUsers.length} users`);
    
    const userIds = finalUsers.map(u => u.id);
    const sampleClients = buildSampleClients(userIds);
    
    console.log("Seeding clients...");
    const insertedClients = await db.insert(clients).values(sampleClients).returning();
    console.log(`Seeded ${insertedClients.length} clients successfully!`);
    
    console.log("Seeding activities...");
    const sampleActivities = [
      { clientId: insertedClients[0].id, action: "Follow-up call completed", userId: finalUsers[0].id },
      { clientId: insertedClients[0].id, action: "Proposal sent", userId: finalUsers[1].id },
      { clientId: insertedClients[0].id, action: "Initial meeting", userId: finalUsers[0].id },
      { clientId: insertedClients[1].id, action: "Pricing discussion", userId: finalUsers[2].id },
      { clientId: insertedClients[1].id, action: "Proposal submitted", userId: finalUsers[0].id },
      { clientId: insertedClients[2].id, action: "Contract signed", userId: finalUsers[1].id },
      { clientId: insertedClients[2].id, action: "Final negotiations", userId: finalUsers[0].id },
      { clientId: insertedClients[3].id, action: "Discovery call", userId: finalUsers[2].id },
      { clientId: insertedClients[4].id, action: "Technical review meeting", userId: finalUsers[0].id },
      { clientId: insertedClients[4].id, action: "Proposal sent", userId: finalUsers[1].id },
      { clientId: insertedClients[5].id, action: "Compliance review scheduled", userId: finalUsers[0].id },
      { clientId: insertedClients[6].id, action: "Demo presentation", userId: finalUsers[2].id },
      { clientId: insertedClients[7].id, action: "Sustainability features discussed", userId: finalUsers[0].id },
      { clientId: insertedClients[9].id, action: "Multi-location requirements gathered", userId: finalUsers[3].id },
      { clientId: insertedClients[10].id, action: "Implementation kickoff scheduled", userId: finalUsers[1].id },
      { clientId: insertedClients[12].id, action: "Integration requirements reviewed", userId: finalUsers[2].id },
      { clientId: insertedClients[14].id, action: "Budget approval pending", userId: finalUsers[0].id },
      { clientId: insertedClients[16].id, action: "Mobile demo provided", userId: finalUsers[3].id },
      { clientId: insertedClients[17].id, action: "Contract finalized", userId: finalUsers[1].id },
      { clientId: insertedClients[19].id, action: "Product demo scheduled", userId: finalUsers[0].id },
    ];
    
    const insertedActivities = await db.insert(activities).values(sampleActivities).returning();
    console.log(`Seeded ${insertedActivities.length} activities successfully!`);
    
    console.log("\n✓ Database seeding completed successfully!");
    console.log(`  - ${insertedUsers.length} users`);
    console.log(`  - ${insertedClients.length} clients`);
    console.log(`  - ${insertedActivities.length} activities`);
    
    process.exit(0);
  } catch (error) {
    console.error("Error during seeding:", error);
    throw error;
  }
}

seed().catch((error) => {
  console.error("Fatal error seeding database:", error);
  process.exit(1);
});
