import { storage } from './storage';

const sampleClients = [
  {
    companyName: 'Acme Corporation',
    contactPerson: 'John Smith',
    email: 'john.smith@acme.com',
    phone: '+1-555-0101',
    stage: 'Won' as const,
    status: undefined,
    value: 250000,
    priority: 'High' as const,
    responsiblePerson: 'Sarah Johnson',
    country: 'United States',
    service: 'Enterprise Solutions',
    linkedin: 'linkedin.com/company/acme',
    notes: 'Long-term contract, renewable annually',
    lastFollowUp: new Date('2024-12-01'),
    nextFollowUp: new Date('2025-01-01'),
    source: 'Referral' as const,
    industry: 'Technology',
    estimatedCloseDate: undefined,
    winProbability: undefined,
  },
  {
    companyName: 'Global Tech Solutions',
    contactPerson: 'Maria Garcia',
    email: 'maria@globaltech.com',
    phone: '+1-555-0102',
    stage: 'Negotiation' as const,
    status: 'In Discussion' as const,
    value: 180000,
    priority: 'High' as const,
    responsiblePerson: 'Michael Chen',
    country: 'Canada',
    service: 'Custom Development',
    linkedin: 'linkedin.com/company/globaltech',
    notes: 'Final pricing negotiations, contract review in progress',
    lastFollowUp: new Date('2024-11-28'),
    nextFollowUp: new Date('2024-12-10'),
    source: 'Website' as const,
    industry: 'Software',
    estimatedCloseDate: new Date('2024-12-15'),
    winProbability: 85,
  },
  {
    companyName: 'Cloud First Innovations',
    contactPerson: 'David Lee',
    email: 'david@cloudfirst.io',
    phone: '+1-555-0103',
    stage: 'Proposal' as const,
    status: 'Proposal Sent' as const,
    value: 95000,
    priority: 'Medium' as const,
    responsiblePerson: 'Emily Davis',
    country: 'United Kingdom',
    service: 'Cloud Infrastructure',
    linkedin: 'linkedin.com/company/cloudfirst',
    notes: 'Waiting for client feedback on proposal',
    lastFollowUp: new Date('2024-11-25'),
    nextFollowUp: new Date('2024-12-08'),
    source: 'Cold Outreach' as const,
    industry: 'Cloud Services',
    estimatedCloseDate: new Date('2024-12-20'),
    winProbability: 60,
  },
  {
    companyName: 'Premium Analytics Inc',
    contactPerson: 'Jessica Wong',
    email: 'jessica@premiumanalytics.com',
    phone: '+44-20-7946-0958',
    stage: 'Qualified' as const,
    status: 'Qualified Lead' as const,
    value: 145000,
    priority: 'High' as const,
    responsiblePerson: 'Robert Wilson',
    country: 'Germany',
    service: 'Analytics Platform',
    linkedin: 'linkedin.com/company/premiumanalytics',
    notes: 'Budget approved, moving to proposal stage next week',
    lastFollowUp: new Date('2024-11-30'),
    nextFollowUp: new Date('2024-12-05'),
    source: 'Event' as const,
    industry: 'Data Analytics',
    estimatedCloseDate: new Date('2025-01-15'),
    winProbability: 75,
  },
  {
    companyName: 'Digital Marketing Hub',
    contactPerson: 'Amanda Rodriguez',
    email: 'amanda@digitalmarketinghub.com',
    phone: '+1-555-0105',
    stage: 'Lead' as const,
    status: 'New Lead' as const,
    value: 65000,
    priority: 'Low' as const,
    responsiblePerson: 'James Martinez',
    country: 'United States',
    service: 'Marketing Automation',
    linkedin: 'linkedin.com/company/dmhub',
    notes: 'Initial contact made, scheduling discovery call',
    lastFollowUp: new Date('2024-11-29'),
    nextFollowUp: new Date('2024-12-12'),
    source: 'Website' as const,
    industry: 'Marketing',
    estimatedCloseDate: new Date('2025-02-01'),
    winProbability: 30,
  },
  {
    companyName: 'Financial Services Group',
    contactPerson: 'Thomas Anderson',
    email: 'thomas@fsglobal.com',
    phone: '+61-2-8000-7000',
    stage: 'Negotiation' as const,
    status: 'Terms Agreed' as const,
    value: 320000,
    priority: 'Critical' as const,
    responsiblePerson: 'Catherine Smith',
    country: 'Australia',
    service: 'Enterprise Solutions',
    linkedin: 'linkedin.com/company/fsglobal',
    notes: 'Legal review scheduled for next week, closing expected mid-January',
    lastFollowUp: new Date('2024-12-02'),
    nextFollowUp: new Date('2024-12-09'),
    source: 'Partner' as const,
    industry: 'Finance',
    estimatedCloseDate: new Date('2025-01-20'),
    winProbability: 90,
  },
  {
    companyName: 'Retail Solutions Network',
    contactPerson: 'Michelle Chen',
    email: 'michelle@retailsol.com',
    phone: '+1-555-0107',
    stage: 'Won' as const,
    status: undefined,
    value: 210000,
    priority: 'High' as const,
    responsiblePerson: 'David Thompson',
    country: 'United States',
    service: 'POS System Integration',
    linkedin: 'linkedin.com/company/retailsol',
    notes: 'Contract signed, implementation starting January',
    lastFollowUp: new Date('2024-11-27'),
    nextFollowUp: new Date('2025-01-05'),
    source: 'Referral' as const,
    industry: 'Retail',
    estimatedCloseDate: undefined,
    winProbability: undefined,
  },
  {
    companyName: 'Healthcare Innovations Ltd',
    contactPerson: 'Dr. Patricia Johnson',
    email: 'patricia@healthcareinno.com',
    phone: '+353-1-5000-100',
    stage: 'Proposal' as const,
    status: 'Under Review' as const,
    value: 275000,
    priority: 'High' as const,
    responsiblePerson: 'Lisa Anderson',
    country: 'Ireland',
    service: 'Custom Development',
    linkedin: 'linkedin.com/company/healthcareinno',
    notes: 'Compliance review ongoing, approval expected by end of month',
    lastFollowUp: new Date('2024-11-26'),
    nextFollowUp: new Date('2024-12-06'),
    source: 'Cold Outreach' as const,
    industry: 'Healthcare',
    estimatedCloseDate: new Date('2024-12-28'),
    winProbability: 70,
  },
  {
    companyName: 'Educational Platforms Co',
    contactPerson: 'Kevin O\'Brien',
    email: 'kevin@eduplatforms.com',
    phone: '+353-1-6700-200',
    stage: 'Lead' as const,
    status: 'New Lead' as const,
    value: 78000,
    priority: 'Medium' as const,
    responsiblePerson: 'Paul O\'Connor',
    country: 'Ireland',
    service: 'Learning Management System',
    linkedin: 'linkedin.com/company/eduplatforms',
    notes: 'Contact made through industry conference',
    lastFollowUp: new Date('2024-12-01'),
    nextFollowUp: new Date('2024-12-15'),
    source: 'Event' as const,
    industry: 'Education',
    estimatedCloseDate: new Date('2025-02-28'),
    winProbability: 40,
  },
  {
    companyName: 'Logistics Express International',
    contactPerson: 'Sofia Volkov',
    email: 'sofia@logisticsexp.com',
    phone: '+7-495-9825-000',
    stage: 'Qualified' as const,
    status: 'Qualified Lead' as const,
    value: 165000,
    priority: 'High' as const,
    responsiblePerson: 'Marcus Johnson',
    country: 'Russia',
    service: 'Supply Chain Solutions',
    linkedin: 'linkedin.com/company/logisticsexp',
    notes: 'Requirements gathering completed, moving to proposal phase',
    lastFollowUp: new Date('2024-11-24'),
    nextFollowUp: new Date('2024-12-11'),
    source: 'Website' as const,
    industry: 'Logistics',
    estimatedCloseDate: new Date('2025-01-30'),
    winProbability: 72,
  },
  {
    companyName: 'Manufacturing Dynamics',
    contactPerson: 'Hugo Schmidt',
    email: 'hugo@mfgdynamics.com',
    phone: '+49-89-6900-0',
    stage: 'Negotiation' as const,
    status: 'In Discussion' as const,
    value: 290000,
    priority: 'High' as const,
    responsiblePerson: 'Sandra Mueller',
    country: 'Germany',
    service: 'IoT Solutions',
    linkedin: 'linkedin.com/company/mfgdynamics',
    notes: 'Final technical specifications being reviewed',
    lastFollowUp: new Date('2024-11-28'),
    nextFollowUp: new Date('2024-12-07'),
    source: 'Partner' as const,
    industry: 'Manufacturing',
    estimatedCloseDate: new Date('2024-12-29'),
    winProbability: 88,
  },
  {
    companyName: 'Energy Solutions Corp',
    contactPerson: 'Yuki Tanaka',
    email: 'yuki@energysol.com',
    phone: '+81-3-6250-7000',
    stage: 'Lost' as const,
    status: undefined,
    value: 120000,
    priority: 'Medium' as const,
    responsiblePerson: 'Brian O\'Sullivan',
    country: 'Japan',
    service: 'Analytics Platform',
    linkedin: 'linkedin.com/company/energysol',
    notes: 'Client selected competitor with lower pricing',
    lastFollowUp: new Date('2024-11-20'),
    nextFollowUp: new Date('2025-02-01'),
    source: 'Website' as const,
    industry: 'Energy',
    estimatedCloseDate: undefined,
    winProbability: undefined,
  },
  {
    companyName: 'Tourism Development Ventures',
    contactPerson: 'Antonio Garcia',
    email: 'antonio@tourismdv.com',
    phone: '+34-91-5000-100',
    stage: 'Lead' as const,
    status: 'Contacted' as const,
    value: 110000,
    priority: 'Medium' as const,
    responsiblePerson: 'Jennifer Walsh',
    country: 'Spain',
    service: 'Booking System',
    linkedin: 'linkedin.com/company/tourismdv',
    notes: 'Awaiting response to initial inquiry',
    lastFollowUp: new Date('2024-11-25'),
    nextFollowUp: new Date('2024-12-14'),
    source: 'Cold Outreach' as const,
    industry: 'Tourism',
    estimatedCloseDate: new Date('2025-03-15'),
    winProbability: 25,
  },
  {
    companyName: 'Fashion Tech Collective',
    contactPerson: 'Elena Rossi',
    email: 'elena@fashiontech.com',
    phone: '+39-02-3660-0000',
    stage: 'Proposal' as const,
    status: 'Proposal Sent' as const,
    value: 88000,
    priority: 'Low' as const,
    responsiblePerson: 'Victoria Martinez',
    country: 'Italy',
    service: 'E-Commerce Platform',
    linkedin: 'linkedin.com/company/fashiontech',
    notes: 'Waiting for design approval before proceeding',
    lastFollowUp: new Date('2024-11-22'),
    nextFollowUp: new Date('2024-12-09'),
    source: 'Referral' as const,
    industry: 'Fashion',
    estimatedCloseDate: new Date('2025-01-25'),
    winProbability: 55,
  },
  {
    companyName: 'Construction Engineering Plus',
    contactPerson: 'Frank Bauer',
    email: 'frank@constructioneng.com',
    phone: '+43-1-5000-0',
    stage: 'Qualified' as const,
    status: 'Qualified Lead' as const,
    value: 200000,
    priority: 'High' as const,
    responsiblePerson: 'Patricia O\'Sullivan',
    country: 'Austria',
    service: 'Project Management Software',
    linkedin: 'linkedin.com/company/constructioneng',
    notes: 'Budget approved, stakeholder alignment in progress',
    lastFollowUp: new Date('2024-11-29'),
    nextFollowUp: new Date('2024-12-13'),
    source: 'Event' as const,
    industry: 'Construction',
    estimatedCloseDate: new Date('2025-02-10'),
    winProbability: 78,
  },
  {
    companyName: 'Agricultural Innovations',
    contactPerson: 'Jaqueline Moreau',
    email: 'jaqueline@agarinnovations.com',
    phone: '+33-1-4567-8900',
    stage: 'Lead' as const,
    status: 'New Lead' as const,
    value: 95000,
    priority: 'Low' as const,
    responsiblePerson: 'Christopher Lee',
    country: 'France',
    service: 'IoT Solutions',
    linkedin: 'linkedin.com/company/agarinnovations',
    notes: 'Initial discovery call scheduled',
    lastFollowUp: new Date('2024-12-02'),
    nextFollowUp: new Date('2024-12-16'),
    source: 'Website' as const,
    industry: 'Agriculture',
    estimatedCloseDate: new Date('2025-03-01'),
    winProbability: 35,
  },
  {
    companyName: 'Telecommunications Plus',
    contactPerson: 'Lars Nielsen',
    email: 'lars@telecomplus.com',
    phone: '+45-3344-5500',
    stage: 'Won' as const,
    status: undefined,
    value: 380000,
    priority: 'Critical' as const,
    responsiblePerson: 'Diane Richardson',
    country: 'Denmark',
    service: 'Enterprise Solutions',
    linkedin: 'linkedin.com/company/telecomplus',
    notes: 'Multi-year agreement signed, onboarding complete',
    lastFollowUp: new Date('2024-11-15'),
    nextFollowUp: new Date('2025-01-15'),
    source: 'Partner' as const,
    industry: 'Telecommunications',
    estimatedCloseDate: undefined,
    winProbability: undefined,
  },
  {
    companyName: 'Media & Broadcasting Hub',
    contactPerson: 'Ingrid Bergman',
    email: 'ingrid@mediahub.com',
    phone: '+46-8-5000-0000',
    stage: 'Negotiation' as const,
    status: 'Terms Agreed' as const,
    value: 155000,
    priority: 'High' as const,
    responsiblePerson: 'Kenneth Adams',
    country: 'Sweden',
    service: 'Streaming Platform',
    linkedin: 'linkedin.com/company/mediahub',
    notes: 'Contract finalization in progress, legal review scheduled',
    lastFollowUp: new Date('2024-11-30'),
    nextFollowUp: new Date('2024-12-10'),
    source: 'Website' as const,
    industry: 'Media',
    estimatedCloseDate: new Date('2024-12-27'),
    winProbability: 92,
  },
  {
    companyName: 'Chemical Research International',
    contactPerson: 'Dr. Nils Bergström',
    email: 'nils@chemresearch.com',
    phone: '+46-8-1234-5678',
    stage: 'Proposal' as const,
    status: 'Under Review' as const,
    value: 225000,
    priority: 'High' as const,
    responsiblePerson: 'Susan Palmer',
    country: 'Sweden',
    service: 'Lab Management System',
    linkedin: 'linkedin.com/company/chemresearch',
    notes: 'Technical feasibility study completed positively',
    lastFollowUp: new Date('2024-11-27'),
    nextFollowUp: new Date('2024-12-08'),
    source: 'Cold Outreach' as const,
    industry: 'Chemicals',
    estimatedCloseDate: new Date('2025-01-10'),
    winProbability: 68,
  },
  {
    companyName: 'Wine Industry Solutions',
    contactPerson: 'Pierre Bonhomme',
    email: 'pierre@winesolutions.com',
    phone: '+33-4-7777-7777',
    stage: 'Lead' as const,
    status: 'New Lead' as const,
    value: 72000,
    priority: 'Low' as const,
    responsiblePerson: 'Gregory Thompson',
    country: 'France',
    service: 'Inventory Management',
    linkedin: 'linkedin.com/company/winesolutions',
    notes: 'Referral from industry contact',
    lastFollowUp: new Date('2024-12-01'),
    nextFollowUp: new Date('2024-12-18'),
    source: 'Referral' as const,
    industry: 'Food & Beverage',
    estimatedCloseDate: new Date('2025-03-30'),
    winProbability: 28,
  },
  {
    companyName: 'Insurance Digital Transformation',
    contactPerson: 'Maria Fernandes',
    email: 'maria@insurancedigital.com',
    phone: '+351-21-3100-100',
    stage: 'Qualified' as const,
    status: 'Qualified Lead' as const,
    value: 310000,
    priority: 'Critical' as const,
    responsiblePerson: 'Michael Brady',
    country: 'Portugal',
    service: 'Digital Transformation',
    linkedin: 'linkedin.com/company/insurancedigital',
    notes: 'Executive sponsor identified, board approval expected next month',
    lastFollowUp: new Date('2024-11-23'),
    nextFollowUp: new Date('2024-12-12'),
    source: 'Event' as const,
    industry: 'Insurance',
    estimatedCloseDate: new Date('2025-02-28'),
    winProbability: 82,
  },
  {
    companyName: 'Blockchain Ventures Ltd',
    contactPerson: 'Alexios Papadopoulos',
    email: 'alexios@blockchainventures.com',
    phone: '+30-21-7200-0000',
    stage: 'Lead' as const,
    status: 'Contacted' as const,
    value: 135000,
    priority: 'Medium' as const,
    responsiblePerson: 'Rachel Green',
    country: 'Greece',
    service: 'Blockchain Solutions',
    linkedin: 'linkedin.com/company/blockchainventures',
    notes: 'Follow-up meeting scheduled after Holidays',
    lastFollowUp: new Date('2024-11-28'),
    nextFollowUp: new Date('2025-01-08'),
    source: 'Website' as const,
    industry: 'Technology',
    estimatedCloseDate: new Date('2025-03-15'),
    winProbability: 42,
  },
  {
    companyName: 'Real Estate Digital Platform',
    contactPerson: 'Robert Kowalski',
    email: 'robert@realestatedigital.com',
    phone: '+48-22-5555-1000',
    stage: 'Proposal' as const,
    status: 'Proposal Sent' as const,
    value: 165000,
    priority: 'High' as const,
    responsiblePerson: 'Jennifer White',
    country: 'Poland',
    service: 'CRM Platform',
    linkedin: 'linkedin.com/company/realestatedigital',
    notes: 'Proposal includes 3-year implementation roadmap',
    lastFollowUp: new Date('2024-11-26'),
    nextFollowUp: new Date('2024-12-09'),
    source: 'Cold Outreach' as const,
    industry: 'Real Estate',
    estimatedCloseDate: new Date('2025-01-31'),
    winProbability: 64,
  },
  {
    companyName: 'Sports Management Global',
    contactPerson: 'Viktor Petrov',
    email: 'viktor@sportsmanagement.com',
    phone: '+7-812-4568-9012',
    stage: 'Negotiation' as const,
    status: 'Price Negotiation' as const,
    value: 185000,
    priority: 'High' as const,
    responsiblePerson: 'Nicole Scott',
    country: 'Russia',
    service: 'Event Management System',
    linkedin: 'linkedin.com/company/sportsmanagement',
    notes: 'Client requesting volume discount, finalizing terms',
    lastFollowUp: new Date('2024-11-29'),
    nextFollowUp: new Date('2024-12-06'),
    source: 'Referral' as const,
    industry: 'Sports',
    estimatedCloseDate: new Date('2024-12-31'),
    winProbability: 86,
  },
  {
    companyName: 'Publishing House Modern',
    contactPerson: 'Elizabeth Thompson',
    email: 'elizabeth@publishinghouse.com',
    phone: '+44-207-946-0958',
    stage: 'Won' as const,
    status: undefined,
    value: 140000,
    priority: 'Medium' as const,
    responsiblePerson: 'Oscar Martin',
    country: 'United Kingdom',
    service: 'Content Management System',
    linkedin: 'linkedin.com/company/publishinghouse',
    notes: 'Contract executed, go-live scheduled for Q1 2025',
    lastFollowUp: new Date('2024-11-20'),
    nextFollowUp: new Date('2025-01-05'),
    source: 'Event' as const,
    industry: 'Publishing',
    estimatedCloseDate: undefined,
    winProbability: undefined,
  },
  {
    companyName: 'Automotive Supply Chain',
    contactPerson: 'Klaus Mueller',
    email: 'klaus@autosupply.com',
    phone: '+49-711-5000-0',
    stage: 'Lead' as const,
    status: 'New Lead' as const,
    value: 250000,
    priority: 'High' as const,
    responsiblePerson: 'Amanda Foster',
    country: 'Germany',
    service: 'Supply Chain Solutions',
    linkedin: 'linkedin.com/company/autosupply',
    notes: 'Large opportunity, requires multiple stakeholder meetings',
    lastFollowUp: new Date('2024-12-02'),
    nextFollowUp: new Date('2024-12-20'),
    source: 'Partner' as const,
    industry: 'Automotive',
    estimatedCloseDate: new Date('2025-04-15'),
    winProbability: 38,
  },
  {
    companyName: 'Pharmaceutical Research Corp',
    contactPerson: 'Dr. Sophie Laurent',
    email: 'sophie@pharmaresearch.com',
    phone: '+33-1-4000-7000',
    stage: 'Qualified' as const,
    status: 'Budget Approved' as const,
    value: 420000,
    priority: 'Critical' as const,
    responsiblePerson: 'Trevor Lloyd',
    country: 'France',
    service: 'Clinical Trial Management',
    linkedin: 'linkedin.com/company/pharmaresearch',
    notes: 'Multi-department approval completed, SOW being prepared',
    lastFollowUp: new Date('2024-11-30'),
    nextFollowUp: new Date('2024-12-11'),
    source: 'Website' as const,
    industry: 'Pharmaceutical',
    estimatedCloseDate: new Date('2025-02-14'),
    winProbability: 89,
  },
  {
    companyName: 'Renewable Energy Systems',
    contactPerson: 'Carlos Sanchez',
    email: 'carlos@renewableenergy.com',
    phone: '+34-93-6000-600',
    stage: 'Lost' as const,
    status: undefined,
    value: 175000,
    priority: 'Medium' as const,
    responsiblePerson: 'Paula Rodriguez',
    country: 'Spain',
    service: 'Energy Management Platform',
    linkedin: 'linkedin.com/company/renewableenergy',
    notes: 'Client opted for internal development instead',
    lastFollowUp: new Date('2024-11-15'),
    nextFollowUp: new Date('2025-02-15'),
    source: 'Cold Outreach' as const,
    industry: 'Energy',
    estimatedCloseDate: undefined,
    winProbability: undefined,
  },
  {
    companyName: 'Hospitality Group International',
    contactPerson: 'Marco Rosini',
    email: 'marco@hospitalitygroup.com',
    phone: '+39-06-5000-0000',
    stage: 'Proposal' as const,
    status: 'Under Review' as const,
    value: 198000,
    priority: 'High' as const,
    responsiblePerson: 'Sylvia Johnson',
    country: 'Italy',
    service: 'Guest Management System',
    linkedin: 'linkedin.com/company/hospitalitygroup',
    notes: 'Proposal includes customization for 50 hotel properties',
    lastFollowUp: new Date('2024-11-25'),
    nextFollowUp: new Date('2024-12-10'),
    source: 'Referral' as const,
    industry: 'Hospitality',
    estimatedCloseDate: new Date('2025-02-01'),
    winProbability: 71,
  },
  {
    companyName: 'Education Tech Innovations',
    contactPerson: 'Priya Sharma',
    email: 'priya@edutech.com',
    phone: '+91-11-4000-0000',
    stage: 'Negotiation' as const,
    status: 'In Discussion' as const,
    value: 125000,
    priority: 'Medium' as const,
    responsiblePerson: 'Victor Chang',
    country: 'India',
    service: 'Online Learning Platform',
    linkedin: 'linkedin.com/company/edutech',
    notes: 'Implementation timeline being finalized',
    lastFollowUp: new Date('2024-11-27'),
    nextFollowUp: new Date('2024-12-07'),
    source: 'Website' as const,
    industry: 'Education',
    estimatedCloseDate: new Date('2025-01-20'),
    winProbability: 79,
  },
  {
    companyName: 'Fintech Disruption Labs',
    contactPerson: 'Rajesh Patel',
    email: 'rajesh@fintechlabs.com',
    phone: '+91-22-6000-0000',
    stage: 'Lead' as const,
    status: 'Contacted' as const,
    value: 220000,
    priority: 'High' as const,
    responsiblePerson: 'Helena Price',
    country: 'India',
    service: 'Payment Processing System',
    linkedin: 'linkedin.com/company/fintechlabs',
    notes: 'Follow-up meeting scheduled for next week',
    lastFollowUp: new Date('2024-11-28'),
    nextFollowUp: new Date('2024-12-11'),
    source: 'Event' as const,
    industry: 'Financial Technology',
    estimatedCloseDate: new Date('2025-03-30'),
    winProbability: 52,
  },
  {
    companyName: 'Mining Operations Ltd',
    contactPerson: 'John Smith',
    email: 'john@miningops.com',
    phone: '+61-8-6000-9000',
    stage: 'Qualified' as const,
    status: 'Qualified Lead' as const,
    value: 550000,
    priority: 'Critical' as const,
    responsiblePerson: 'Louise Mitchell',
    country: 'Australia',
    service: 'Operations Management Suite',
    linkedin: 'linkedin.com/company/miningops',
    notes: 'Large deal requiring executive alignment, budget already approved',
    lastFollowUp: new Date('2024-11-24'),
    nextFollowUp: new Date('2024-12-12'),
    source: 'Partner' as const,
    industry: 'Mining',
    estimatedCloseDate: new Date('2025-03-01'),
    winProbability: 85,
  },
  {
    companyName: 'Consumer Goods Distribution',
    contactPerson: 'Natasha Volkova',
    email: 'natasha@goodsdist.com',
    phone: '+7-495-6789-0000',
    stage: 'Proposal' as const,
    status: 'Proposal Sent' as const,
    value: 142000,
    priority: 'Medium' as const,
    responsiblePerson: 'Walter Harris',
    country: 'Russia',
    service: 'Distribution Management',
    linkedin: 'linkedin.com/company/goodsdist',
    notes: 'Proposal covers 15-warehouse network implementation',
    lastFollowUp: new Date('2024-11-21'),
    nextFollowUp: new Date('2024-12-12'),
    source: 'Website' as const,
    industry: 'Consumer Goods',
    estimatedCloseDate: new Date('2025-02-28'),
    winProbability: 67,
  },
  {
    companyName: 'Aviation Services Inc',
    contactPerson: 'Michael O\'Shea',
    email: 'michael@aviationservices.com',
    phone: '+1-888-555-0132',
    stage: 'Won' as const,
    status: undefined,
    value: 365000,
    priority: 'High' as const,
    responsiblePerson: 'Diana Norton',
    country: 'United States',
    service: 'Maintenance Management System',
    linkedin: 'linkedin.com/company/aviationservices',
    notes: 'Tier-1 fleet operators, multi-year agreement signed',
    lastFollowUp: new Date('2024-11-10'),
    nextFollowUp: new Date('2025-01-10'),
    source: 'Referral' as const,
    industry: 'Aviation',
    estimatedCloseDate: undefined,
    winProbability: undefined,
  },
  {
    companyName: 'Environmental Solutions Group',
    contactPerson: 'Emma Green',
    email: 'emma@envirosolutions.com',
    phone: '+44-121-3000-000',
    stage: 'Lead' as const,
    status: 'New Lead' as const,
    value: 95000,
    priority: 'Low' as const,
    responsiblePerson: 'Derek Hayes',
    country: 'United Kingdom',
    service: 'Environmental Monitoring',
    linkedin: 'linkedin.com/company/envirosolutions',
    notes: 'Initial consultation call pending',
    lastFollowUp: new Date('2024-12-02'),
    nextFollowUp: new Date('2024-12-19'),
    source: 'Website' as const,
    industry: 'Environmental',
    estimatedCloseDate: new Date('2025-03-30'),
    winProbability: 32,
  },
  {
    companyName: 'Quality Assurance Technologies',
    contactPerson: 'Brian Murphy',
    email: 'brian@qatech.com',
    phone: '+1-617-555-0145',
    stage: 'Negotiation' as const,
    status: 'Terms Agreed' as const,
    value: 175000,
    priority: 'High' as const,
    responsiblePerson: 'Karen Lewis',
    country: 'United States',
    service: 'Testing Automation Platform',
    linkedin: 'linkedin.com/company/qatech',
    notes: 'Final contract review, expected closure before year-end',
    lastFollowUp: new Date('2024-11-30'),
    nextFollowUp: new Date('2024-12-08'),
    source: 'Cold Outreach' as const,
    industry: 'Software Quality',
    estimatedCloseDate: new Date('2024-12-23'),
    winProbability: 94,
  },
  {
    companyName: 'Legal Tech Innovations',
    contactPerson: 'Jennifer Hayes',
    email: 'jennifer@legaltech.com',
    phone: '+1-212-555-0156',
    stage: 'Lead' as const,
    status: 'Contacted' as const,
    value: 160000,
    priority: 'Medium' as const,
    responsiblePerson: 'Edward Webb',
    country: 'United States',
    service: 'Case Management System',
    linkedin: 'linkedin.com/company/legaltech',
    notes: 'Discovery call completed, requirements gathering phase',
    lastFollowUp: new Date('2024-11-29'),
    nextFollowUp: new Date('2024-12-16'),
    source: 'Event' as const,
    industry: 'Legal Services',
    estimatedCloseDate: new Date('2025-03-20'),
    winProbability: 48,
  },
  {
    companyName: 'Telecommunications Infrastructure',
    contactPerson: 'Wei Chen',
    email: 'wei@telecominfra.com',
    phone: '+86-10-8000-0000',
    stage: 'Proposal' as const,
    status: 'Awaiting Budget' as const,
    value: 485000,
    priority: 'Critical' as const,
    responsiblePerson: 'Monica Patel',
    country: 'China',
    service: 'Network Management Platform',
    linkedin: 'linkedin.com/company/telecominfra',
    notes: 'Large enterprise deal, requires board approval expected in January',
    lastFollowUp: new Date('2024-11-19'),
    nextFollowUp: new Date('2024-12-15'),
    source: 'Partner' as const,
    industry: 'Telecommunications',
    estimatedCloseDate: new Date('2025-02-20'),
    winProbability: 76,
  },
  {
    companyName: 'Smart City Development Co',
    contactPerson: 'Ahmed Hassan',
    email: 'ahmed@smartcity.com',
    phone: '+966-11-2000-0000',
    stage: 'Lead' as const,
    status: 'New Lead' as const,
    value: 720000,
    priority: 'Critical' as const,
    responsiblePerson: 'Fatima Khan',
    country: 'Saudi Arabia',
    service: 'IoT Platform',
    linkedin: 'linkedin.com/company/smartcity',
    notes: 'Government project, very large opportunity, multiple stakeholders',
    lastFollowUp: new Date('2024-12-01'),
    nextFollowUp: new Date('2024-12-20'),
    source: 'Referral' as const,
    industry: 'Smart City',
    estimatedCloseDate: new Date('2025-05-30'),
    winProbability: 45,
  },
  {
    companyName: 'Logistics Optimization Platform',
    contactPerson: 'Thomas Wagner',
    email: 'thomas@logisticsopt.com',
    phone: '+49-201-5000-100',
    stage: 'Won' as const,
    status: undefined,
    value: 295000,
    priority: 'High' as const,
    responsiblePerson: 'Rebecca Foster',
    country: 'Germany',
    service: 'Route Optimization',
    linkedin: 'linkedin.com/company/logisticsopt',
    notes: 'Implementation timeline established for Q1 2025',
    lastFollowUp: new Date('2024-11-18'),
    nextFollowUp: new Date('2025-01-08'),
    source: 'Event' as const,
    industry: 'Logistics',
    estimatedCloseDate: undefined,
    winProbability: undefined,
  },
  {
    companyName: 'Waste Management Solutions',
    contactPerson: 'Patricia Schmidt',
    email: 'patricia@wastemgt.com',
    phone: '+43-1-7000-0000',
    stage: 'Qualified' as const,
    status: 'Budget Approved' as const,
    value: 210000,
    priority: 'High' as const,
    responsiblePerson: 'Samuel Cook',
    country: 'Austria',
    service: 'Fleet Management',
    linkedin: 'linkedin.com/company/wastemgt',
    notes: 'All approvals in place, moving to proposal stage this week',
    lastFollowUp: new Date('2024-11-26'),
    nextFollowUp: new Date('2024-12-10'),
    source: 'Website' as const,
    industry: 'Waste Management',
    estimatedCloseDate: new Date('2025-01-31'),
    winProbability: 87,
  },
  {
    companyName: 'Security Systems Global',
    contactPerson: 'Luis Rodriguez',
    email: 'luis@securitysystemsglobal.com',
    phone: '+34-28-5000-0000',
    stage: 'Proposal' as const,
    status: 'Under Review' as const,
    value: 165000,
    priority: 'High' as const,
    responsiblePerson: 'Michelle Young',
    country: 'Spain',
    service: 'Access Control System',
    linkedin: 'linkedin.com/company/securitysystemsglobal',
    notes: 'Technical requirements agreed, awaiting management approval',
    lastFollowUp: new Date('2024-11-28'),
    nextFollowUp: new Date('2024-12-09'),
    source: 'Cold Outreach' as const,
    industry: 'Security',
    estimatedCloseDate: new Date('2025-01-30'),
    winProbability: 73,
  },
  {
    companyName: 'Water Utility Services',
    contactPerson: 'Henrik Larsson',
    email: 'henrik@waterutility.com',
    phone: '+46-8-5000-0000',
    stage: 'Lost' as const,
    status: undefined,
    value: 185000,
    priority: 'Medium' as const,
    responsiblePerson: 'Nicole Taylor',
    country: 'Sweden',
    service: 'Infrastructure Management',
    linkedin: 'linkedin.com/company/waterutility',
    notes: 'Budget reallocated to different project, follow up Q3 2025',
    lastFollowUp: new Date('2024-11-10'),
    nextFollowUp: new Date('2025-07-01'),
    source: 'Website' as const,
    industry: 'Utilities',
    estimatedCloseDate: undefined,
    winProbability: undefined,
  },
  {
    companyName: 'Bakery Operations Network',
    contactPerson: 'Francoise Martin',
    email: 'francoise@bakerysops.com',
    phone: '+33-1-5000-0000',
    stage: 'Lead' as const,
    status: 'New Lead' as const,
    value: 78000,
    priority: 'Low' as const,
    responsiblePerson: 'Patrick Evans',
    country: 'France',
    service: 'Inventory System',
    linkedin: 'linkedin.com/company/bakerysops',
    notes: 'Small SME, initial inquiry received',
    lastFollowUp: new Date('2024-12-02'),
    nextFollowUp: new Date('2024-12-20'),
    source: 'Website' as const,
    industry: 'Food & Beverage',
    estimatedCloseDate: new Date('2025-04-15'),
    winProbability: 22,
  },
  {
    companyName: 'Technology Infrastructure Corp',
    contactPerson: 'Andrew Thomson',
    email: 'andrew@techinfra.com',
    phone: '+1-206-555-0167',
    stage: 'Negotiation' as const,
    status: 'Price Negotiation' as const,
    value: 405000,
    priority: 'Critical' as const,
    responsiblePerson: 'Carolyn Miller',
    country: 'United States',
    service: 'Data Center Management',
    linkedin: 'linkedin.com/company/techinfra',
    notes: 'Client negotiating multi-year discount, nearly ready to close',
    lastFollowUp: new Date('2024-12-01'),
    nextFollowUp: new Date('2024-12-08'),
    source: 'Referral' as const,
    industry: 'Technology',
    estimatedCloseDate: new Date('2024-12-29'),
    winProbability: 91,
  },
  {
    companyName: 'Cooperative Farming Ventures',
    contactPerson: 'Olaf Bergmann',
    email: 'olaf@coopfarming.com',
    phone: '+49-341-5000-000',
    stage: 'Qualified' as const,
    status: 'Qualified Lead' as const,
    value: 125000,
    priority: 'Medium' as const,
    responsiblePerson: 'Natalie Phillips',
    country: 'Germany',
    service: 'Farm Management Software',
    linkedin: 'linkedin.com/company/coopfarming',
    notes: 'Pilot program approved, ready for proposal phase',
    lastFollowUp: new Date('2024-11-22'),
    nextFollowUp: new Date('2024-12-10'),
    source: 'Event' as const,
    industry: 'Agriculture',
    estimatedCloseDate: new Date('2025-02-15'),
    winProbability: 74,
  },
];

export async function seedDatabase() {
  try {
    console.log('Seeding database with 50 sample clients...');
    
    for (const clientData of sampleClients) {
      await storage.createClient({
        companyName: clientData.companyName,
        contactPerson: clientData.contactPerson,
        email: clientData.email,
        phone: clientData.phone,
        stage: clientData.stage,
        status: clientData.status,
        value: clientData.value,
        priority: clientData.priority,
        responsiblePerson: clientData.responsiblePerson,
        country: clientData.country,
        service: clientData.service,
        linkedin: clientData.linkedin,
        notes: clientData.notes,
        lastFollowUp: clientData.lastFollowUp,
        nextFollowUp: clientData.nextFollowUp,
        source: clientData.source,
        industry: clientData.industry,
        estimatedCloseDate: clientData.estimatedCloseDate,
        winProbability: clientData.winProbability,
        activityHistory: [],
      } as any);
    }
    
    console.log('Successfully seeded 50 sample clients!');
    return true;
  } catch (error) {
    console.error('Error seeding database:', error);
    throw error;
  }
}
