import { drizzle } from "drizzle-orm/neon-serverless";
import { clients, users, activities, services, clientStageHistory } from "../shared/schema";
import ws from "ws";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is required");
}

const db = drizzle({
  connection: process.env.DATABASE_URL,
  ws: ws,
});

const sampleUsers = [
  { name: "Sarah Johnson", email: "sarah@cybaemtech.com", role: "Sales Rep" as const },
  { name: "Mike Davis", email: "mike@cybaemtech.com", role: "Manager" as const },
  { name: "Tom Williams", email: "tom@cybaemtech.com", role: "Sales Rep" as const },
  { name: "Jennifer Lee", email: "jennifer@cybaemtech.com", role: "Sales Rep" as const },
  { name: "Alex Martinez", email: "alex@cybaemtech.com", role: "Sales Rep" as const },
  { name: "Rachel Chen", email: "rachel@cybaemtech.com", role: "Sales Rep" as const },
  { name: "David Kim", email: "david@cybaemtech.com", role: "Admin" as const },
];

const sampleServices = [
  { name: "Product Development", isActive: "true" },
  { name: "CRM", isActive: "true" },
  { name: "ERP", isActive: "true" },
  { name: "Mobile Development", isActive: "true" },
  { name: "Website Creation", isActive: "true" },
  { name: "Digital Marketing", isActive: "true" },
  { name: "ITSM", isActive: "true" },
  { name: "Cloud Migration", isActive: "true" },
  { name: "Data Analytics", isActive: "true" },
  { name: "Cybersecurity", isActive: "true" },
];

const buildSampleClients = (userIds: string[], serviceIds: string[]) => [
  {
    companyName: "Acme Corporation",
    contactPerson: "John Smith",
    email: "john@acme.com",
    phone: "+1 234-567-8900",
    stage: "Qualified" as const,
    status: "In Negotiation" as const,
    value: "250000",
    lastFollowUp: new Date("2025-11-15"),
    nextFollowUp: new Date("2025-12-10"),
    priority: "High" as const,
    responsiblePersonId: userIds[0],
    serviceId: serviceIds[0],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/johnsmith",
    notes: "Interested in enterprise package. Decision maker meeting scheduled.",
    source: "Referral" as const,
    industry: "Technology",
    estimatedCloseDate: new Date("2026-01-15"),
    winProbability: 75,
  },
  {
    companyName: "TechStart Inc",
    contactPerson: "Emily Chen",
    email: "emily@techstart.com",
    phone: "+1 555-123-4567",
    stage: "Proposal Sent" as const,
    status: "Pending Review" as const,
    value: "180000",
    lastFollowUp: new Date("2025-11-20"),
    nextFollowUp: new Date("2025-12-05"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[2],
    serviceId: serviceIds[1],
    country: "Canada",
    linkedin: "https://www.linkedin.com/in/emilychen",
    notes: "Looking for more flexible pricing options.",
    source: "Website" as const,
    industry: "SaaS",
    estimatedCloseDate: new Date("2026-01-30"),
    winProbability: 55,
  },
  {
    companyName: "Global Solutions Ltd",
    contactPerson: "Robert Taylor",
    email: "robert@globalsolutions.com",
    phone: "+1 555-987-6543",
    stage: "Won" as const,
    status: null,
    value: "420000",
    lastFollowUp: new Date("2025-11-17"),
    nextFollowUp: new Date("2025-12-01"),
    priority: "High" as const,
    responsiblePersonId: userIds[1],
    serviceId: serviceIds[2],
    country: "United Kingdom",
    linkedin: "https://www.linkedin.com/in/roberttaylor",
    notes: "Contract signed. Awaiting project kick-off.",
    source: "Event" as const,
    industry: "Consulting",
    estimatedCloseDate: new Date("2025-11-17"),
    winProbability: 100,
  },
  {
    companyName: "Innovation Hub",
    contactPerson: "Lisa Anderson",
    email: "lisa@innovationhub.com",
    phone: "+1 555-456-7890",
    stage: "Lead" as const,
    status: "Awaiting Response" as const,
    value: "95000",
    lastFollowUp: new Date("2025-11-25"),
    nextFollowUp: new Date("2025-12-08"),
    priority: "Low" as const,
    responsiblePersonId: userIds[3],
    serviceId: serviceIds[3],
    country: "Australia",
    linkedin: "",
    notes: "Initial contact made. Needs more information.",
    source: "Cold Outreach" as const,
    industry: "Retail",
    estimatedCloseDate: new Date("2026-03-01"),
    winProbability: 20,
  },
  {
    companyName: "FutureTech Systems",
    contactPerson: "David Wu",
    email: "david@futuretech.com",
    phone: "+1 555-789-0123",
    stage: "Proposal Sent" as const,
    status: "In Negotiation" as const,
    value: "320000",
    lastFollowUp: new Date("2025-11-22"),
    nextFollowUp: new Date("2025-12-06"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    serviceId: serviceIds[4],
    country: "Singapore",
    linkedin: "https://www.linkedin.com/in/davidwu",
    notes: "Strong interest. Reviewing technical requirements.",
    source: "Partner" as const,
    industry: "Manufacturing",
    estimatedCloseDate: new Date("2026-01-20"),
    winProbability: 65,
  },
  {
    companyName: "Metro Banking Group",
    contactPerson: "Patricia Williams",
    email: "patricia@metrobank.com",
    phone: "+1 415-555-0100",
    stage: "Qualified" as const,
    status: "Under Evaluation" as const,
    value: "580000",
    lastFollowUp: new Date("2025-11-28"),
    nextFollowUp: new Date("2025-12-12"),
    priority: "High" as const,
    responsiblePersonId: userIds[0],
    serviceId: serviceIds[5],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/patriciawilliams",
    notes: "Large enterprise deal. Requires compliance review and multiple stakeholder approval.",
    source: "Referral" as const,
    industry: "Financial Services",
    estimatedCloseDate: new Date("2026-02-15"),
    winProbability: 80,
  },
  {
    companyName: "HealthPlus Medical",
    contactPerson: "Dr. Michael Chang",
    email: "mchang@healthplus.com",
    phone: "+1 617-555-0200",
    stage: "Lead" as const,
    status: null,
    value: "125000",
    lastFollowUp: new Date("2025-11-18"),
    nextFollowUp: new Date("2025-12-02"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[2],
    serviceId: serviceIds[6],
    country: "United States",
    linkedin: "",
    notes: "Healthcare provider looking for patient management system.",
    source: "Website" as const,
    industry: "Healthcare",
    estimatedCloseDate: new Date("2026-02-01"),
    winProbability: 40,
  },
  {
    companyName: "EcoEnergy Solutions",
    contactPerson: "Sandra Martinez",
    email: "sandra@ecoenergy.com",
    phone: "+1 303-555-0300",
    stage: "Proposal Sent" as const,
    status: "Pending Review" as const,
    value: "275000",
    lastFollowUp: new Date("2025-11-24"),
    nextFollowUp: new Date("2025-12-07"),
    priority: "High" as const,
    responsiblePersonId: userIds[1],
    serviceId: serviceIds[7],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/sandramartinez",
    notes: "Renewable energy company. Very interested in sustainability features.",
    source: "Event" as const,
    industry: "Energy",
    estimatedCloseDate: new Date("2026-01-10"),
    winProbability: 70,
  },
  {
    companyName: "Digital Media Pro",
    contactPerson: "James Thompson",
    email: "james@digitalmedia.com",
    phone: "+1 212-555-0400",
    stage: "Lead" as const,
    status: "Awaiting Response" as const,
    value: "90000",
    lastFollowUp: new Date("2025-11-20"),
    nextFollowUp: new Date("2025-12-04"),
    priority: "Low" as const,
    responsiblePersonId: userIds[3],
    serviceId: serviceIds[8],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/jamesthompson",
    notes: "Small marketing agency. Budget constraints noted.",
    source: "Cold Outreach" as const,
    industry: "Marketing",
    estimatedCloseDate: new Date("2026-03-15"),
    winProbability: 25,
  },
  {
    companyName: "Phoenix Logistics",
    contactPerson: "Carlos Rodriguez",
    email: "carlos@phoenixlog.com",
    phone: "+52 55-5555-0500",
    stage: "Qualified" as const,
    status: "In Negotiation" as const,
    value: "340000",
    lastFollowUp: new Date("2025-11-26"),
    nextFollowUp: new Date("2025-12-10"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    serviceId: serviceIds[9],
    country: "Mexico",
    linkedin: "https://www.linkedin.com/in/carlosrodriguez",
    notes: "International logistics company expanding to North America. Multi-location deployment.",
    source: "Partner" as const,
    industry: "Logistics",
    estimatedCloseDate: new Date("2026-01-25"),
    winProbability: 60,
  },
  {
    companyName: "BlueSky Aviation",
    contactPerson: "Amanda Foster",
    email: "amanda@blueskyair.com",
    phone: "+1 404-555-0600",
    stage: "Won" as const,
    status: null,
    value: "650000",
    lastFollowUp: new Date("2025-11-15"),
    nextFollowUp: new Date("2025-12-15"),
    priority: "High" as const,
    responsiblePersonId: userIds[0],
    serviceId: serviceIds[0],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/amandafoster",
    notes: "Contract finalized. Implementation starts December 1st. Requires on-site training.",
    source: "Referral" as const,
    industry: "Aviation",
    estimatedCloseDate: new Date("2025-11-15"),
    winProbability: 100,
  },
  {
    companyName: "Quantum Analytics",
    contactPerson: "Dr. Raj Patel",
    email: "raj@quantumanalytics.com",
    phone: "+91 22-5555-0700",
    stage: "Lost" as const,
    status: "Proposal Rejected" as const,
    value: "210000",
    lastFollowUp: new Date("2025-11-16"),
    nextFollowUp: new Date("2026-03-01"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[2],
    serviceId: serviceIds[1],
    country: "India",
    linkedin: "https://www.linkedin.com/in/rajpatel",
    notes: "Pricing too high for current budget. May revisit in Q1 2026.",
    source: "Website" as const,
    industry: "Data Analytics",
    estimatedCloseDate: null,
    winProbability: 0,
  },
  {
    companyName: "Prime Real Estate Group",
    contactPerson: "Michelle Lee",
    email: "michelle@primerealestate.com",
    phone: "+1 310-555-0800",
    stage: "Qualified" as const,
    status: "Pending Review" as const,
    value: "195000",
    lastFollowUp: new Date("2025-11-27"),
    nextFollowUp: new Date("2025-12-11"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[1],
    serviceId: serviceIds[2],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/michellelee",
    notes: "Commercial real estate firm. Interested in CRM integration with their property management system.",
    source: "Event" as const,
    industry: "Real Estate",
    estimatedCloseDate: new Date("2026-01-30"),
    winProbability: 55,
  },
  {
    companyName: "Nordic Manufacturing",
    contactPerson: "Lars Andersson",
    email: "lars@nordicmfg.com",
    phone: "+46 8-555-0900",
    stage: "Lead" as const,
    status: null,
    value: "410000",
    lastFollowUp: new Date("2025-11-21"),
    nextFollowUp: new Date("2025-12-05"),
    priority: "High" as const,
    responsiblePersonId: userIds[3],
    serviceId: serviceIds[3],
    country: "Sweden",
    linkedin: "https://www.linkedin.com/in/larsandersson",
    notes: "Large manufacturing operation. Requires multi-language support and EU data compliance.",
    source: "Partner" as const,
    industry: "Manufacturing",
    estimatedCloseDate: new Date("2026-03-01"),
    winProbability: 50,
  },
  {
    companyName: "StarBridge Telecommunications",
    contactPerson: "Kevin O'Brien",
    email: "kevin@starbridge.com",
    phone: "+353 1-555-1000",
    stage: "Proposal Sent" as const,
    status: "On Hold" as const,
    value: "525000",
    lastFollowUp: new Date("2025-11-23"),
    nextFollowUp: new Date("2026-01-15"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    serviceId: serviceIds[4],
    country: "Ireland",
    linkedin: "https://www.linkedin.com/in/kevinobrien",
    notes: "Internal restructuring delayed decision. Very interested but waiting for new fiscal year.",
    source: "Referral" as const,
    industry: "Telecommunications",
    estimatedCloseDate: new Date("2026-02-15"),
    winProbability: 70,
  },
  {
    companyName: "Oceanic Research Institute",
    contactPerson: "Dr. Maria Santos",
    email: "maria@oceanicresearch.org",
    phone: "+55 21-555-1100",
    stage: "Lead" as const,
    status: "Awaiting Response" as const,
    value: "85000",
    lastFollowUp: new Date("2025-11-19"),
    nextFollowUp: new Date("2025-12-03"),
    priority: "Low" as const,
    responsiblePersonId: userIds[0],
    serviceId: serviceIds[5],
    country: "Brazil",
    linkedin: "",
    notes: "Non-profit research organization. Grant-dependent budget.",
    source: "Website" as const,
    industry: "Research",
    estimatedCloseDate: new Date("2026-04-01"),
    winProbability: 30,
  },
  {
    companyName: "Velocity Sports Management",
    contactPerson: "Derek Johnson",
    email: "derek@velocitysports.com",
    phone: "+1 702-555-1200",
    stage: "Qualified" as const,
    status: "Under Evaluation" as const,
    value: "160000",
    lastFollowUp: new Date("2025-11-29"),
    nextFollowUp: new Date("2025-12-13"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[2],
    serviceId: serviceIds[6],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/derekjohnson",
    notes: "Sports talent agency. Needs mobile-first solution for agents in the field.",
    source: "Cold Outreach" as const,
    industry: "Sports & Entertainment",
    estimatedCloseDate: new Date("2026-02-20"),
    winProbability: 45,
  },
  {
    companyName: "Silverline Insurance",
    contactPerson: "Rebecca Zhang",
    email: "rebecca@silverlineins.com",
    phone: "+1 972-555-1300",
    stage: "Won" as const,
    status: null,
    value: "385000",
    lastFollowUp: new Date("2025-11-14"),
    nextFollowUp: new Date("2025-12-14"),
    priority: "High" as const,
    responsiblePersonId: userIds[1],
    serviceId: serviceIds[7],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/rebeccazhang",
    notes: "Deal closed. Regional insurance provider. Implementation phase starting.",
    source: "Event" as const,
    industry: "Insurance",
    estimatedCloseDate: new Date("2025-11-14"),
    winProbability: 100,
  },
  {
    companyName: "Alpine Construction Group",
    contactPerson: "Stefan Mueller",
    email: "stefan@alpineconstruction.com",
    phone: "+41 44-555-1400",
    stage: "Proposal Sent" as const,
    status: "Under Evaluation" as const,
    value: "295000",
    lastFollowUp: new Date("2025-11-25"),
    nextFollowUp: new Date("2025-12-09"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[3],
    serviceId: serviceIds[8],
    country: "Switzerland",
    linkedin: "https://www.linkedin.com/in/stefanmueller",
    notes: "Construction management company. Evaluating against two competitors.",
    source: "Partner" as const,
    industry: "Construction",
    estimatedCloseDate: new Date("2026-02-15"),
    winProbability: 50,
  },
  {
    companyName: "Nexus Education Platform",
    contactPerson: "Priya Sharma",
    email: "priya@nexusedu.com",
    phone: "+65 6555-1500",
    stage: "Qualified" as const,
    status: "In Negotiation" as const,
    value: "225000",
    lastFollowUp: new Date("2025-11-30"),
    nextFollowUp: new Date("2025-12-14"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    serviceId: serviceIds[9],
    country: "Singapore",
    linkedin: "https://www.linkedin.com/in/priyasharma",
    notes: "EdTech startup scaling rapidly. Strong growth potential for upsell opportunities.",
    source: "Referral" as const,
    industry: "Education Technology",
    estimatedCloseDate: new Date("2026-01-10"),
    winProbability: 75,
  },
  {
    companyName: "Summit Healthcare Partners",
    contactPerson: "Dr. Angela Morrison",
    email: "amorrison@summithp.com",
    phone: "+1 602-555-1600",
    stage: "Demo Completed" as const,
    status: "Under Evaluation" as const,
    value: "445000",
    lastFollowUp: new Date("2025-11-28"),
    nextFollowUp: new Date("2025-12-12"),
    priority: "High" as const,
    responsiblePersonId: userIds[0],
    serviceId: serviceIds[0],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/angelamorrison",
    notes: "Multi-location healthcare network. Very impressed with demo. HIPAA compliance confirmed.",
    source: "Referral" as const,
    industry: "Healthcare",
    estimatedCloseDate: new Date("2026-01-30"),
    winProbability: 80,
  },
  {
    companyName: "Pacific Rim Trading",
    contactPerson: "Ken Tanaka",
    email: "ken@pacificrimtrading.com",
    phone: "+81 3-5555-1700",
    stage: "Meeting Scheduled" as const,
    status: "Awaiting Response" as const,
    value: "380000",
    lastFollowUp: new Date("2025-11-22"),
    nextFollowUp: new Date("2025-12-06"),
    priority: "High" as const,
    responsiblePersonId: userIds[1],
    serviceId: serviceIds[1],
    country: "Japan",
    linkedin: "https://www.linkedin.com/in/kentanaka",
    notes: "Import/export company. Interested in multi-currency and localization features.",
    source: "Partner" as const,
    industry: "Trading",
    estimatedCloseDate: new Date("2026-02-28"),
    winProbability: 65,
  },
  {
    companyName: "Cornerstone Financial",
    contactPerson: "Richard Barnes",
    email: "rbarnes@cornerstonefin.com",
    phone: "+1 312-555-1800",
    stage: "Contract Review" as const,
    status: "In Negotiation" as const,
    value: "720000",
    lastFollowUp: new Date("2025-11-30"),
    nextFollowUp: new Date("2025-12-07"),
    priority: "High" as const,
    responsiblePersonId: userIds[2],
    serviceId: serviceIds[2],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/richardbarnes",
    notes: "Large financial services firm. Contract in legal review. Expected to close by year-end.",
    source: "Referral" as const,
    industry: "Financial Services",
    estimatedCloseDate: new Date("2025-12-31"),
    winProbability: 90,
  },
  {
    companyName: "Redwood Pharmaceuticals",
    contactPerson: "Dr. Sarah Chen",
    email: "schen@redwoodpharma.com",
    phone: "+1 858-555-1900",
    stage: "Proof of Concept (POC)" as const,
    status: "Under Evaluation" as const,
    value: "550000",
    lastFollowUp: new Date("2025-11-27"),
    nextFollowUp: new Date("2025-12-11"),
    priority: "High" as const,
    responsiblePersonId: userIds[3],
    serviceId: serviceIds[3],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/sarahchenpharma",
    notes: "Pharmaceutical company running 30-day POC. FDA compliance requirements.",
    source: "Event" as const,
    industry: "Pharmaceuticals",
    estimatedCloseDate: new Date("2026-02-15"),
    winProbability: 70,
  },
  {
    companyName: "Atlas Shipping Corp",
    contactPerson: "George Papadopoulos",
    email: "george@atlasshipping.com",
    phone: "+30 210-555-2000",
    stage: "Verbal Commitment" as const,
    status: "Budget Approval Pending" as const,
    value: "490000",
    lastFollowUp: new Date("2025-11-29"),
    nextFollowUp: new Date("2025-12-06"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    serviceId: serviceIds[4],
    country: "Greece",
    linkedin: "https://www.linkedin.com/in/georgepapadopoulos",
    notes: "Maritime shipping company. Verbal yes from CEO. Awaiting board budget approval.",
    source: "Partner" as const,
    industry: "Maritime",
    estimatedCloseDate: new Date("2026-01-15"),
    winProbability: 85,
  },
  {
    companyName: "TerraGreen Agriculture",
    contactPerson: "Maria Rodriguez",
    email: "maria@terragreen.com",
    phone: "+1 559-555-2100",
    stage: "Demo Completed" as const,
    status: "Awaiting Response" as const,
    value: "175000",
    lastFollowUp: new Date("2025-11-24"),
    nextFollowUp: new Date("2025-12-08"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[0],
    serviceId: serviceIds[5],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/mariarodriguezag",
    notes: "Agricultural technology company. Interested in IoT integration capabilities.",
    source: "Website" as const,
    industry: "Agriculture",
    estimatedCloseDate: new Date("2026-02-28"),
    winProbability: 55,
  },
  {
    companyName: "CityLink Transport",
    contactPerson: "Thomas Brown",
    email: "tbrown@citylinktransport.com",
    phone: "+44 20-555-2200",
    stage: "Proposal Sent" as const,
    status: "Pending Review" as const,
    value: "310000",
    lastFollowUp: new Date("2025-11-26"),
    nextFollowUp: new Date("2025-12-10"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[1],
    serviceId: serviceIds[6],
    country: "United Kingdom",
    linkedin: "https://www.linkedin.com/in/thomasbrownuk",
    notes: "Public transport operator. Need fleet management integration.",
    source: "Cold Outreach" as const,
    industry: "Transportation",
    estimatedCloseDate: new Date("2026-02-01"),
    winProbability: 50,
  },
  {
    companyName: "Luxe Hotels International",
    contactPerson: "Francois Dubois",
    email: "fdubois@luxehotels.com",
    phone: "+33 1-555-2300",
    stage: "Qualified" as const,
    status: "In Negotiation" as const,
    value: "475000",
    lastFollowUp: new Date("2025-11-28"),
    nextFollowUp: new Date("2025-12-12"),
    priority: "High" as const,
    responsiblePersonId: userIds[2],
    serviceId: serviceIds[7],
    country: "France",
    linkedin: "https://www.linkedin.com/in/francoisdubois",
    notes: "Luxury hotel chain with 50+ properties. Multi-property deployment required.",
    source: "Event" as const,
    industry: "Hospitality",
    estimatedCloseDate: new Date("2026-03-01"),
    winProbability: 60,
  },
  {
    companyName: "Bright Minds Academy",
    contactPerson: "Dr. William Peters",
    email: "wpeters@brightminds.edu",
    phone: "+1 617-555-2400",
    stage: "Lead" as const,
    status: null,
    value: "120000",
    lastFollowUp: new Date("2025-11-20"),
    nextFollowUp: new Date("2025-12-04"),
    priority: "Low" as const,
    responsiblePersonId: userIds[3],
    serviceId: serviceIds[8],
    country: "United States",
    linkedin: "",
    notes: "Private K-12 school network. Budget cycle starts in April.",
    source: "Website" as const,
    industry: "Education",
    estimatedCloseDate: new Date("2026-05-01"),
    winProbability: 35,
  },
  {
    companyName: "Zenith Aerospace",
    contactPerson: "Captain James Wright",
    email: "jwright@zenithaero.com",
    phone: "+1 206-555-2500",
    stage: "Won" as const,
    status: null,
    value: "890000",
    lastFollowUp: new Date("2025-11-10"),
    nextFollowUp: new Date("2025-12-10"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    serviceId: serviceIds[9],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/jameswright",
    notes: "Aerospace defense contractor. Major enterprise deal. Multi-year contract.",
    source: "Referral" as const,
    industry: "Aerospace & Defense",
    estimatedCloseDate: new Date("2025-11-10"),
    winProbability: 100,
  },
  {
    companyName: "Golden Gate Ventures",
    contactPerson: "Victoria Chang",
    email: "vchang@ggventures.com",
    phone: "+1 415-555-2600",
    stage: "Meeting Scheduled" as const,
    status: null,
    value: "265000",
    lastFollowUp: new Date("2025-11-25"),
    nextFollowUp: new Date("2025-12-09"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[0],
    serviceId: serviceIds[0],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/victoriachang",
    notes: "Venture capital firm. Looking for portfolio company management solution.",
    source: "Referral" as const,
    industry: "Venture Capital",
    estimatedCloseDate: new Date("2026-02-15"),
    winProbability: 45,
  },
  {
    companyName: "Aurora Biotech",
    contactPerson: "Dr. Elizabeth Harper",
    email: "eharper@aurorabio.com",
    phone: "+1 858-555-2700",
    stage: "Demo Completed" as const,
    status: "Under Evaluation" as const,
    value: "385000",
    lastFollowUp: new Date("2025-11-27"),
    nextFollowUp: new Date("2025-12-11"),
    priority: "High" as const,
    responsiblePersonId: userIds[1],
    serviceId: serviceIds[1],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/elizabethharper",
    notes: "Biotech startup. Recently received Series B funding. Fast decision-making process.",
    source: "Partner" as const,
    industry: "Biotechnology",
    estimatedCloseDate: new Date("2026-01-15"),
    winProbability: 70,
  },
  {
    companyName: "Royal Crown Mining",
    contactPerson: "Peter MacKenzie",
    email: "pmackenzie@rcmining.com",
    phone: "+61 2-555-2800",
    stage: "Proposal Sent" as const,
    status: "Pending Review" as const,
    value: "620000",
    lastFollowUp: new Date("2025-11-23"),
    nextFollowUp: new Date("2025-12-07"),
    priority: "High" as const,
    responsiblePersonId: userIds[2],
    serviceId: serviceIds[2],
    country: "Australia",
    linkedin: "https://www.linkedin.com/in/petermackenzie",
    notes: "Mining company with remote operations. Offline capability is key requirement.",
    source: "Event" as const,
    industry: "Mining",
    estimatedCloseDate: new Date("2026-02-28"),
    winProbability: 65,
  },
  {
    companyName: "Tokyo Electronics",
    contactPerson: "Yuki Yamamoto",
    email: "yyamamoto@tokyoelec.co.jp",
    phone: "+81 3-555-2900",
    stage: "Lead" as const,
    status: "Awaiting Response" as const,
    value: "340000",
    lastFollowUp: new Date("2025-11-21"),
    nextFollowUp: new Date("2025-12-05"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[3],
    serviceId: serviceIds[3],
    country: "Japan",
    linkedin: "https://www.linkedin.com/in/yukiyamamoto",
    notes: "Consumer electronics manufacturer. Initial inquiry for ERP integration.",
    source: "Website" as const,
    industry: "Electronics",
    estimatedCloseDate: new Date("2026-04-01"),
    winProbability: 40,
  },
  {
    companyName: "Harvest Foods Co",
    contactPerson: "Susan Miller",
    email: "smiller@harvestfoods.com",
    phone: "+1 515-555-3000",
    stage: "Qualified" as const,
    status: "Under Evaluation" as const,
    value: "195000",
    lastFollowUp: new Date("2025-11-26"),
    nextFollowUp: new Date("2025-12-10"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[4],
    serviceId: serviceIds[4],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/susanmiller",
    notes: "Food processing company. FDA and USDA compliance requirements.",
    source: "Cold Outreach" as const,
    industry: "Food & Beverage",
    estimatedCloseDate: new Date("2026-03-01"),
    winProbability: 50,
  },
  {
    companyName: "Berlin Tech Hub",
    contactPerson: "Klaus Weber",
    email: "kweber@berlintechhub.de",
    phone: "+49 30-555-3100",
    stage: "Contract Review" as const,
    status: "Pending Review" as const,
    value: "285000",
    lastFollowUp: new Date("2025-11-29"),
    nextFollowUp: new Date("2025-12-13"),
    priority: "High" as const,
    responsiblePersonId: userIds[0],
    serviceId: serviceIds[5],
    country: "Germany",
    linkedin: "https://www.linkedin.com/in/klausweber",
    notes: "Tech incubator. Contract under legal review. Strong champion internally.",
    source: "Partner" as const,
    industry: "Technology",
    estimatedCloseDate: new Date("2026-01-15"),
    winProbability: 85,
  },
  {
    companyName: "Coastal Realty Group",
    contactPerson: "Jennifer Adams",
    email: "jadams@coastalrealty.com",
    phone: "+1 305-555-3200",
    stage: "Lost" as const,
    status: "Proposal Rejected" as const,
    value: "145000",
    lastFollowUp: new Date("2025-11-15"),
    nextFollowUp: new Date("2026-05-01"),
    priority: "Low" as const,
    responsiblePersonId: userIds[1],
    serviceId: serviceIds[6],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/jenniferadams",
    notes: "Chose competitor solution. Open to revisit in 6 months for potential migration.",
    source: "Referral" as const,
    industry: "Real Estate",
    estimatedCloseDate: null,
    winProbability: 0,
  },
  {
    companyName: "NovaStar Media",
    contactPerson: "Christopher Lee",
    email: "clee@novastarmedia.com",
    phone: "+1 323-555-3300",
    stage: "Proposal Sent" as const,
    status: "In Negotiation" as const,
    value: "230000",
    lastFollowUp: new Date("2025-11-28"),
    nextFollowUp: new Date("2025-12-12"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[2],
    serviceId: serviceIds[7],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/christopherlee",
    notes: "Entertainment production company. Need content management and rights tracking.",
    source: "Event" as const,
    industry: "Entertainment",
    estimatedCloseDate: new Date("2026-02-01"),
    winProbability: 55,
  },
  {
    companyName: "Swiss Precision Engineering",
    contactPerson: "Hans Brunner",
    email: "hbrunner@swissprecision.ch",
    phone: "+41 44-555-3400",
    stage: "Proof of Concept (POC)" as const,
    status: "In Negotiation" as const,
    value: "415000",
    lastFollowUp: new Date("2025-11-27"),
    nextFollowUp: new Date("2025-12-11"),
    priority: "High" as const,
    responsiblePersonId: userIds[3],
    serviceId: serviceIds[8],
    country: "Switzerland",
    linkedin: "https://www.linkedin.com/in/hansbrunner",
    notes: "Precision manufacturing company. Running 45-day POC. Very technical requirements.",
    source: "Partner" as const,
    industry: "Manufacturing",
    estimatedCloseDate: new Date("2026-02-15"),
    winProbability: 75,
  },
  {
    companyName: "Cape Town Wines",
    contactPerson: "Willem van der Berg",
    email: "wvdberg@capetownwines.co.za",
    phone: "+27 21-555-3500",
    stage: "Lead" as const,
    status: null,
    value: "95000",
    lastFollowUp: new Date("2025-11-19"),
    nextFollowUp: new Date("2025-12-03"),
    priority: "Low" as const,
    responsiblePersonId: userIds[4],
    serviceId: serviceIds[9],
    country: "South Africa",
    linkedin: "",
    notes: "Wine producer and exporter. Initial inquiry for inventory and distribution tracking.",
    source: "Website" as const,
    industry: "Wine & Spirits",
    estimatedCloseDate: new Date("2026-04-01"),
    winProbability: 30,
  },
  {
    companyName: "MetroCity Development",
    contactPerson: "Andrew Collins",
    email: "acollins@metrocitydev.com",
    phone: "+1 214-555-3600",
    stage: "Demo Completed" as const,
    status: "Awaiting Response" as const,
    value: "365000",
    lastFollowUp: new Date("2025-11-26"),
    nextFollowUp: new Date("2025-12-10"),
    priority: "High" as const,
    responsiblePersonId: userIds[0],
    serviceId: serviceIds[0],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/andrewcollins",
    notes: "Commercial real estate developer. Demo well received. Waiting for CFO approval.",
    source: "Referral" as const,
    industry: "Real Estate Development",
    estimatedCloseDate: new Date("2026-01-31"),
    winProbability: 65,
  },
  {
    companyName: "Singapore FinTech Solutions",
    contactPerson: "Alan Tan",
    email: "atan@sgfintech.com",
    phone: "+65 6555-3700",
    stage: "Verbal Commitment" as const,
    status: "Pending Review" as const,
    value: "310000",
    lastFollowUp: new Date("2025-11-30"),
    nextFollowUp: new Date("2025-12-07"),
    priority: "High" as const,
    responsiblePersonId: userIds[1],
    serviceId: serviceIds[1],
    country: "Singapore",
    linkedin: "https://www.linkedin.com/in/alantan",
    notes: "FinTech company. Verbal commitment received. Final contract review in progress.",
    source: "Partner" as const,
    industry: "FinTech",
    estimatedCloseDate: new Date("2025-12-31"),
    winProbability: 90,
  },
  {
    companyName: "Heritage Arts Foundation",
    contactPerson: "Catherine Reynolds",
    email: "creynolds@heritagearts.org",
    phone: "+1 202-555-3800",
    stage: "Qualified" as const,
    status: "Pending Review" as const,
    value: "135000",
    lastFollowUp: new Date("2025-11-24"),
    nextFollowUp: new Date("2025-12-08"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[2],
    serviceId: serviceIds[2],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/catherinereynolds",
    notes: "Non-profit arts organization. Grant funding secured. Needs donor management.",
    source: "Event" as const,
    industry: "Non-profit",
    estimatedCloseDate: new Date("2026-02-28"),
    winProbability: 55,
  },
  {
    companyName: "Mumbai Tech Park",
    contactPerson: "Rahul Kapoor",
    email: "rkapoor@mumbaitechpark.com",
    phone: "+91 22-555-3900",
    stage: "Meeting Scheduled" as const,
    status: "Awaiting Response" as const,
    value: "280000",
    lastFollowUp: new Date("2025-11-23"),
    nextFollowUp: new Date("2025-12-07"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[3],
    serviceId: serviceIds[3],
    country: "India",
    linkedin: "https://www.linkedin.com/in/rahulkapoor",
    notes: "Technology park management company. Meeting scheduled with decision makers.",
    source: "Cold Outreach" as const,
    industry: "Real Estate",
    estimatedCloseDate: new Date("2026-03-15"),
    winProbability: 45,
  },
  {
    companyName: "Nordic Shipping Lines",
    contactPerson: "Erik Johansson",
    email: "ejohansson@nordicshipping.com",
    phone: "+47 22-555-4000",
    stage: "Proposal Sent" as const,
    status: "Under Evaluation" as const,
    value: "455000",
    lastFollowUp: new Date("2025-11-25"),
    nextFollowUp: new Date("2025-12-09"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    serviceId: serviceIds[4],
    country: "Norway",
    linkedin: "https://www.linkedin.com/in/erikjohansson",
    notes: "Shipping company with 30+ vessels. Need fleet management and crew scheduling.",
    source: "Partner" as const,
    industry: "Maritime",
    estimatedCloseDate: new Date("2026-02-28"),
    winProbability: 60,
  },
  {
    companyName: "Evergreen Solar Tech",
    contactPerson: "Michael Green",
    email: "mgreen@evergreensolar.com",
    phone: "+1 480-555-4100",
    stage: "Won" as const,
    status: null,
    value: "520000",
    lastFollowUp: new Date("2025-11-12"),
    nextFollowUp: new Date("2025-12-12"),
    priority: "High" as const,
    responsiblePersonId: userIds[0],
    serviceId: serviceIds[5],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/michaelgreen",
    notes: "Solar energy company. Contract signed. Implementation starting Q1 2026.",
    source: "Referral" as const,
    industry: "Renewable Energy",
    estimatedCloseDate: new Date("2025-11-12"),
    winProbability: 100,
  },
  {
    companyName: "Dubai Investment Group",
    contactPerson: "Mohammed Al-Rashid",
    email: "malrashid@dubaiinvest.ae",
    phone: "+971 4-555-4200",
    stage: "Contract Review" as const,
    status: "In Negotiation" as const,
    value: "780000",
    lastFollowUp: new Date("2025-11-29"),
    nextFollowUp: new Date("2025-12-06"),
    priority: "High" as const,
    responsiblePersonId: userIds[1],
    serviceId: serviceIds[6],
    country: "UAE",
    linkedin: "https://www.linkedin.com/in/mohammedalrashid",
    notes: "Investment holding company. Large deal in final contract negotiations.",
    source: "Partner" as const,
    industry: "Investment",
    estimatedCloseDate: new Date("2026-01-15"),
    winProbability: 85,
  },
  {
    companyName: "Melbourne Fashion House",
    contactPerson: "Olivia Turner",
    email: "oturner@melbfashion.com.au",
    phone: "+61 3-555-4300",
    stage: "Lead" as const,
    status: "Awaiting Response" as const,
    value: "110000",
    lastFollowUp: new Date("2025-11-20"),
    nextFollowUp: new Date("2025-12-04"),
    priority: "Low" as const,
    responsiblePersonId: userIds[2],
    serviceId: serviceIds[7],
    country: "Australia",
    linkedin: "https://www.linkedin.com/in/oliviaturner",
    notes: "Fashion retailer. Initial discovery call scheduled. Seasonal business.",
    source: "Website" as const,
    industry: "Retail Fashion",
    estimatedCloseDate: new Date("2026-04-01"),
    winProbability: 30,
  },
  {
    companyName: "Pacific Coast Beverages",
    contactPerson: "Ryan Mitchell",
    email: "rmitchell@pacificcoastbev.com",
    phone: "+1 503-555-4400",
    stage: "Qualified" as const,
    status: "Under Evaluation" as const,
    value: "185000",
    lastFollowUp: new Date("2025-11-27"),
    nextFollowUp: new Date("2025-12-11"),
    priority: "Medium" as const,
    responsiblePersonId: userIds[3],
    serviceId: serviceIds[8],
    country: "United States",
    linkedin: "https://www.linkedin.com/in/ryanmitchell",
    notes: "Craft beverage distributor. Looking for inventory and distribution management.",
    source: "Event" as const,
    industry: "Food & Beverage",
    estimatedCloseDate: new Date("2026-02-15"),
    winProbability: 55,
  },
  {
    companyName: "Amsterdam Tech Ventures",
    contactPerson: "Jan de Vries",
    email: "jdevries@amsterdamtechv.com",
    phone: "+31 20-555-4500",
    stage: "Demo Completed" as const,
    status: "Under Evaluation" as const,
    value: "295000",
    lastFollowUp: new Date("2025-11-28"),
    nextFollowUp: new Date("2025-12-12"),
    priority: "High" as const,
    responsiblePersonId: userIds[4],
    serviceId: serviceIds[9],
    country: "Netherlands",
    linkedin: "https://www.linkedin.com/in/jandevries",
    notes: "European venture capital firm. Very impressed with demo. Making final evaluation.",
    source: "Partner" as const,
    industry: "Venture Capital",
    estimatedCloseDate: new Date("2026-01-31"),
    winProbability: 70,
  },
];

async function seed() {
  console.log("Starting database seed...");
  
  try {
    // Clear existing data in proper order (due to foreign keys)
    console.log("Clearing existing data...");
    await db.delete(clientStageHistory);
    await db.delete(activities);
    await db.delete(clients);
    await db.delete(services);
    await db.delete(users);
    
    console.log("Seeding users...");
    const insertedUsers = await db.insert(users).values(sampleUsers).returning();
    console.log(`Inserted ${insertedUsers.length} users`);
    
    console.log("Seeding services...");
    const insertedServices = await db.insert(services).values(sampleServices).returning();
    console.log(`Inserted ${insertedServices.length} services`);
    
    const userIds = insertedUsers.map(u => u.id);
    const serviceIds = insertedServices.map(s => s.id);
    const sampleClients = buildSampleClients(userIds, serviceIds);
    
    console.log("Seeding clients...");
    const insertedClients = await db.insert(clients).values(sampleClients).returning();
    console.log(`Seeded ${insertedClients.length} clients successfully!`);
    
    // Generate activities for each client
    console.log("Seeding activities...");
    const activityTemplates = [
      "Initial discovery call completed",
      "Product demo scheduled",
      "Demo presentation delivered",
      "Proposal document sent",
      "Follow-up call with stakeholders",
      "Technical requirements gathered",
      "Pricing discussion held",
      "Contract terms negotiated",
      "Reference call arranged",
      "Site visit completed",
      "POC kickoff meeting",
      "Integration planning session",
      "Security review completed",
      "Final presentation to leadership",
      "Contract signed",
    ];
    
    const allActivities = [];
    for (const client of insertedClients) {
      const numActivities = Math.floor(Math.random() * 4) + 2; // 2-5 activities per client
      const usedTemplates = new Set<number>();
      
      for (let i = 0; i < numActivities; i++) {
        let templateIdx;
        do {
          templateIdx = Math.floor(Math.random() * activityTemplates.length);
        } while (usedTemplates.has(templateIdx) && usedTemplates.size < activityTemplates.length);
        usedTemplates.add(templateIdx);
        
        const daysAgo = Math.floor(Math.random() * 60) + 1;
        const activityDate = new Date();
        activityDate.setDate(activityDate.getDate() - daysAgo);
        
        allActivities.push({
          clientId: client.id,
          action: activityTemplates[templateIdx],
          userId: userIds[Math.floor(Math.random() * userIds.length)],
          createdAt: activityDate,
        });
      }
    }
    
    const insertedActivities = await db.insert(activities).values(allActivities).returning();
    console.log(`Seeded ${insertedActivities.length} activities successfully!`);
    
    // Generate stage history for each client
    console.log("Seeding stage history...");
    const stages = [
      "Lead", "Qualified", "Meeting Scheduled", "Demo Completed",
      "Proof of Concept (POC)", "Proposal Sent", "Verbal Commitment",
      "Contract Review", "Won", "Lost"
    ] as const;
    
    const allStageHistory = [];
    for (const client of insertedClients) {
      const currentStageIndex = stages.indexOf(client.stage as typeof stages[number]);
      
      let enteredAt = new Date(client.createdAt);
      enteredAt.setDate(enteredAt.getDate() - Math.floor(Math.random() * 30));
      
      // Create history for stages up to current stage
      for (let s = 0; s <= Math.min(currentStageIndex, stages.length - 1); s++) {
        const isCurrentStage = s === currentStageIndex;
        const durationDays = Math.floor(Math.random() * 14) + 1;
        
        let exitedAt = null;
        let durationSeconds = null;
        
        if (!isCurrentStage) {
          exitedAt = new Date(enteredAt.getTime() + durationDays * 24 * 60 * 60 * 1000);
          durationSeconds = durationDays * 24 * 60 * 60;
        }
        
        allStageHistory.push({
          clientId: client.id,
          stage: stages[s],
          enteredAt,
          exitedAt,
          durationSeconds,
          createdAt: enteredAt,
        });
        
        if (exitedAt) {
          enteredAt = exitedAt;
        }
      }
    }
    
    const insertedHistory = await db.insert(clientStageHistory).values(allStageHistory).returning();
    console.log(`Seeded ${insertedHistory.length} stage history records successfully!`);
    
    console.log("\nDatabase seeding completed successfully!");
    console.log(`  - ${insertedUsers.length} users`);
    console.log(`  - ${insertedServices.length} services`);
    console.log(`  - ${insertedClients.length} clients`);
    console.log(`  - ${insertedActivities.length} activities`);
    console.log(`  - ${insertedHistory.length} stage history records`);
    
    process.exit(0);
  } catch (error) {
    console.error("Error during seeding:", error);
    throw error;
  }
}

seed().catch((error) => {
  console.error("Fatal error seeding database:", error);
  process.exit(1);
});
